name: Auto-create pull request on merge to staging

on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'staging'

      - name: Set Git config
        run: |
          git config --global user.name "vasantkumardev"
          git config --global user.email "vasant84kumar@gmail.com"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Merge staging into master'
          body: 'Automatically created pull request to merge branch staging into master'
          head: ${{ github.head_ref }}
          base: 'master'
          delete-branch: false

