name: Compare and Merge Staging to Master

on:
  push:
    branches:
      - staging

jobs:
  compare-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'staging'
          
      - name: Set Git config
        run: |
          git config --global user.name "vasantkumardev"
          git config --global user.email "vasant84kumar@gmail.com"
          
      - name: Compare staging to master
        id: compare
        run: |
          git fetch origin master
          git diff --name-only origin/master..HEAD > changes.txt
          echo "::set-output name=changes::$(cat changes.txt)"
          
      - name: Create merge branch
        run: |
          git checkout -b merge-staging-to-master
          cat changes.txt | xargs git add
          git commit -m "Merge changes from staging to master"
          git push origin merge-staging-to-master
          
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Merge staging into master'
          body: 'Automatically created pull request to merge changes from staging branch into master'
          head: 'merge-staging-to-master'
          base: 'master'
          delete-branch: flase
