name: My Workflow

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  create_pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: master
          head_branch: staging
          title: "Merge Staging to Master"
          body: "Created by GitHub Action"
