on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  create_pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        run: gh pr create -B master -H staging --title 'Merge Staging to master ' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
